## Meta service start-up url
## K8s meta service cluster master-standby high availability scenario: ClusterIP address
## Non-HA scenario: keep consistent with the same name configuration in mmc-meta.conf
ock.mmc.meta_service_url = tcp://192.168.0.48:5000

## Config store url, it will automatically modified to PodIP at Pod startup in HA scenario
## Keep consistent with the same name configuration in mmc-meta.conf
ock.mmc.local_service.config_store_url = tcp://192.168.0.48:6000

## Log level: debug, info, warn, error
ock.mmc.log_level = info

## The maximum supported rank count; once ranks are connected, no further modifications are allowed — a meta restart is required
ock.mmc.local_service.world_size = 256

## Data transfer protocol options:
#   'device_rdma': RDMA over device, direct data transfer between NPUs, optimized for cluster communication
#   'device_sdma': SDMA over device, efficient data transfer using device DMA engine
#   'host_shm': Shared memory over host, inter-process communication within the same node
#   'host_urma': RDMA over host UB, user-space RDMA for high-speed data transfer
#   'host_rdma': RDMA over host, high-speed cross-node data transfer with low latency and high bandwidth
#   'host_tcp': TCP over host, general network transfer with broad compatibility
## Dependencies: host_rdma, host_urma and host_tcp require hcom library; host_shm has no external dependencies
ock.mmc.local_service.protocol = device_sdma

## DRAM space usage, configuration type supports 134217728, 2048KB/2048K, 200MB/200mb/200m, 2.5GB or 1TB, case-insensitive, the maximum value is 1TB
## The system automatically calculates and aligns upwards to 2MB (host_rdma, host_tcp or host_shm) or 1GB (device_sdma or device_rdma)
## In A3 environment all protocol should be aligned to 1GB, otherwise mmc init will fail
## After alignment, the HBM size and DRAM size cannot both be 0 at the same time
ock.mmc.local_service.dram.size = 10GB

## For more configuration options and advanced parameters, please refer to the official documentation: [MemCache Configuration Guide](https://gitcode.com/Ascend/memcache/blob/master/doc/memcache_config.md)
ock.mmc.local_service.max.dram.size=1024G
